---
dontChroot: false
timeout: 600
verbose: true
script:
  - command: "/usr/local/lib/oxsystemsos/cleanup-installed-target"
    timeout: 600
    verbose: true
i18n:
  name: "Clean up installer artifacts"
